### ISSUE TITLE
Support for thinkpad trackpoint's middle button

### ISSUE THREAD

**Issue by amosbird** [Lexikos/AutoHotkey_L#36]
It will add a lot functionalities for thinkpad users to play around.

**Comment by Lexikos** [comment]
Is that a request?

I do not have a ThinkPad, have no idea what's special about it's middle button, and have no interest in adding any features specific to one line of laptop.

**Comment by HotKeyIt** [comment]
The middle button is configured in Control Panel -> Mouse -> UltraNav -> TrackPoint -> settings.
Set it to neither if you like it to act as MButton.
