### ISSUE TITLE
why there is some crappy characters in file script2.cpp at line 1023?

### ISSUE THREAD

**Issue by chapgaga** [Lexikos/AutoHotkey_L#37]
![](http://img.itc.cn/photo/jfeZtkDOXG8.jpg)
http://img.itc.cn/photo/jfeZtkDOXG8.jpg

**Comment by fincs** [comment]
![http://fincs.ahk4.net/files/a.jpg](http://fincs.ahk4.net/files/a.jpg)

**Comment by joedf** [comment]
@chapgaga sort of a list of the encoded characters

**Comment by jhertel** [comment]
Don't call the characters of my language crappy! :-D We need them in Danish
and in many other languages I speak. It's just English that is overly
simplistic. :-D ;-)

Joke aside, I do know what you actually meant. :-)
Den 08/04/2015 19.58 skrev "chapgaga" <notifications@github.com>:

**Comment by Lexikos** [comment]
It's the list of characters referenced by the comment above it, whether that comment is accurate or not.

why is there some crappy question in the issue tracker...?

**Comment by chapgaga** [comment]
@joedf i mean when i open this file using vs 2013, an alert window will be showed up telling there is some crapp characters in this source file:( 
@fincs has these misbehaved charaters been  removed?

**Comment by chapgaga** [comment]
@Lexikos  ![](http://img.itc.cn/photo/jfvn6GbVaDH.jpg)
only few files will encouter this problem, seems it's encoding problem, why this happens?
http://img.itc.cn/photo/jfvn6GbVaDH.jpg

**Comment by Lexikos** [comment]
@chapgaga 
If you read the alert, you will see it is trying to load the file with "Chinese Simplified (GB2312)" encoding.  This is the wrong encoding.  Commit aaec6fb6 solves this problem by changing all files to use UTF-8 with BOM instead of CP1252.
