### ISSUE TITLE
MsgBox (1 > 2) returns the wrong answer, is this a bug ?

### ISSUE THREAD

**Issue by chapgaga** [Lexikos/AutoHotkey_L#38]
![](http://img.itc.cn/photo/jfBLH9d8A4p)

i think i should alert false

**Comment by joedf** [comment]
Show your code.

**Comment by chapgaga** [comment]
@joedf 
^!b::
MsgBox (1>2)
return

i think it should alert false

**Comment by Lexikos** [comment]
Anyone who has learned the basics of AutoHotkey knows that MsgBox accepts plain text by default, not an expression. You must write it like this:

    MsgBox % (1>2)

If you have any other questions, please post them on [the forum](http://ahkscript.org/boards/), not here.
