### ISSUE TITLE
making DLL and use in other application

### ISSUE THREAD

**Issue by RYG81** [Lexikos/AutoHotkey_L#42]
Hi
Is it possible to make DLL of AutoHotkey and use it inside other application development?
I want to use it inside game development macro recording.
Rahul

**Comment by joedf** [comment]
AutoHotkey_H
https://github.com/HotKeyIt/ahkdll-v1-release

**Comment by RYG81** [comment]
Thanks for the quick response.
Where can we learn usage of DLL?

**Comment by joedf** [comment]
http://hotkeyit.github.io/v2/
The downloads should include documentation.

**Comment by RYG81** [comment]
I tried them in Unity3d with reflector, nothing get reflected.
Do you have any knowledge in using it with Unity game aengine?

**Comment by joedf** [comment]
euh... I have done that specifically before...
Maybe you could post some code here for review?

**Comment by RYG81** [comment]
I am using this unity package which does automatic reflection for any code or dll file.
http://www.icanscript.com/
No nee to write code for reflecting.

**Comment by RYG81** [comment]
If you have done that before why not suggest something for this.

**Comment by joedf** [comment]
oh sorry, it was a typo... i forgot a not somewhere in there hahah :P
