### ISSUE TITLE
use AHK to run eclipse will make eclipse error

### ISSUE THREAD

**Issue by kingname** [Lexikos/AutoHotkey_L#48]
My Eclipse is located at D:\eclipse, and while I double-click the eclipse.exe, it will run normally. However, while I use AHK to set: 

`!E::
	run, D:\eclipse\eclipse.exe`

and I press ALT+E to start the eclipse, sometimes eclipse will launch, but alert a dialogBox and say the eclipse UI error. althouth eclipse could still be usable.

This problem will not occur all the time, just some time.

**Comment by Lexikos** [comment]
`Run` uses CreateProcess to launch whatever command line you specify (in some cases it uses ShellExecuteEx, but generally not when given a simple exe). This part of the Run command's functionality is extremely simple and very widely used.  There is just no way that this can be an AutoHotkey bug.

I suggest that you ask for help in the AutoHotkey forum, as other users may have encountered the problem.  Alternatively, I would suggest asking about whatever error message you are getting within a community dedicated to Eclipse.

**Comment by joedf** [comment]
Does this work for you?
`!E:: run, %comspec% start /c D:\eclipse\eclipse.exe`

**Comment by kingname** [comment]
I will try, thx~
