### ISSUE TITLE
The cmd.exe runned by AHK can't run some command

### ISSUE THREAD

**Issue by mercury233** [Lexikos/AutoHotkey_L#49]
I'm using AHK v1.1.22.09 on win7x64sp1.

When I run cmd in ahk script, the commandline window works weirdly. It can't run some system commands such as "bcdedit".

![image](https://cloud.githubusercontent.com/assets/13391795/11533685/f9e0b8a6-9945-11e5-979c-c8b6e1c04ee6.png)

It looks like the PATH environment variable was corrupted, but other cmd.exe runned by WIN+R works well, and PATH don't appear to be wrong. I navigated to system32, but bcdedit still can't run.

Some programs could be used, such as taskmgr, taskkill.

BTW, the taskmgr runned by the "weird" cmd can't show some progress's commandline.

**Comment by joedf** [comment]
Have you tried typing 'bcdedit.exe' instead of 'bcdedit' ?

**Comment by mercury233** [comment]
@joedf It don't work neither.

**Comment by Lexikos** [comment]
AutoHotkey is not responsible for the behaviour of other programs. There are two versions of cmd.exe, and you are running the wrong one. Search the forums for "SysNative".

**Comment by mercury233** [comment]
Thanks, `Run %windir%\Sysnative\cmd.exe` works.
