### ISSUE TITLE
[request] JoyStick viberation monitor

### ISSUE THREAD

**Issue by hbq0449** [Lexikos/AutoHotkey_L#50]
Sorry for the bad English.
More and more games a now supporting the joysticks. From the help doc. I found a script to monitor the input from the Joysticks. Some game support some special input from the joystick, and some special event trigger a viberation in the Joystick.  So I come up with two idea:
 - Monitor the viberation event. 
```cpp
viberation::
    do some stuff
```
 - Simulate joystick input.

I think It will be fascinating.

**Comment by Lexikos** [comment]
I have no idea if it's even possible to detect without hooking the API which is used to set the vibration. It is not something I am interested in pursuing.
