### ISSUE TITLE
UTF-8 support broken in 1.1.23.00

### ISSUE THREAD

**Issue by ilmaisin** [Lexikos/AutoHotkey_L#51]
In the ahk2exe bundled with AHK 1.1.23.00, there is a problem with UTF-8 support. If I try to run a script with UTF-8 characters, i get the following error message:

![ahk_error](https://cloud.githubusercontent.com/assets/8974526/12465021/bb9457fa-bfd4-11e5-92f7-c6f33ffe5a05.png).

The problem is reproducible for example with a simple one-line script containing text `ö::c`. The previous version 11.22.09 works fine. I am running Windows Embedded 8.1 Industry Pro.

**Comment by joedf** [comment]
This is what I was trying to discuss here: 
https://github.com/fincs/Ahk2Exe/pull/41#issuecomment-162408745

However, it was decided to leave it as so.
Your current issue can be worked around by using  `/cp UTF-8`.

**Comment by fincs** [comment]
See fincs/Ahk2Exe@264889146bfa285e69c9a5c3042f6833dd1e5519.

**Comment by joedf** [comment]
Ok great. :+1:

**Comment by ilmaisin** [comment]
ke, 2016-01-20 kello 14:32 -0800, Joe DF kirjoitti:
> This is what I was trying to discuss here: 
> fincs/Ahk2Exe#41 (comment)
> However, it was decided to leave it as so.
> Your current issue can be worked around by using /cp UTF-8.

I tried that command line option and it does the trick. But I think
this should definitely be fixed asap. Bugs like this can't be tolerated
in released software. This makes current ahk2exe release next to
unusable for locales that need accented characters.

-- Iiro Laiho

**Comment by joedf** [comment]
@fincs has already made a commit to fix this.
This regression will be gone in the next release.
