### ISSUE TITLE
issues about Parentheses

### ISSUE THREAD

**Issue by SoVieTing** [Lexikos/AutoHotkey_L#52]
examples:
1.WinWait, test(1).txt - Notepad ahk_class Notepad,,3
2.ControlGet, Var, checked, , Button6, test(2) ahk_class #32770

When include Parentheses in WinTitle, 'winwait' and 'controlget' does not work.
Is that a bug?

**Comment by joedf** [comment]
It's not a bug.
Please refer to the help forums: 
https://autohotkey.com/boards/viewforum.php?f=5&sid=1eaee11878091198a20701eccbf710e0

**Comment by SoVieTing** [comment]
i can't register ahkforum in china right now, i've tried.
can u tell me what's wrong with the parentheses in wintitle?please.

**Comment by joedf** [comment]
There's nothing wrong with the parentheses, it is the misordering of the commas. Your ahk_class is incorrectly used. Why can you register in the forums? What is the problem? No activation email?

**Comment by SoVieTing** [comment]
it's the GFW thing. u know,in china the 'great firewall' blocked some website.

i found this:
SetTitleMatchMode RegEx
i should use EscapeChar
WinWait, test\(1\).txt - Notepad ahk_class Notepad,,3
my bad,thanks for ur time :)

**Comment by joedf** [comment]
Ok I see. Glad it works for you. :+1:
