### ISSUE TITLE
Trojan:Win32/Varpes.M!d

### ISSUE THREAD

**Issue by CanadianJeff** [Lexikos/AutoHotkey_L#54]
Windows Defender on Windows 10 showed this....

```
Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
containerfile:C:\Users\Jeffery\Downloads\AutoHotkey112303_Install.exe
file:C:\Users\Jeffery\Downloads\AutoHotkey112303_Install.exe->(7zSfx)->Compiler/ANSI 32-bit.bin
webfile:C:\Users\Jeffery\Downloads\AutoHotkey112303_Install.exe|https://autohotkey.com/download/1.1/AutoHotkey112303_Install.exe|chrome.exe
```

SHA256 Sum
```
a95c1d32b669d95ce6c2a0e3cc1467b226fba3a6b6a7a4fd675fd16115cb2365  AutoHotkey112303_Install.exe
```

VirusTotal Link
https://www.virustotal.com/en/file/a95c1d32b669d95ce6c2a0e3cc1467b226fba3a6b6a7a4fd675fd16115cb2365/analysis/1458479563/

**Comment by CanadianJeff** [comment]
Detection ratio:	7 / 56

**Comment by hi5** [comment]
False positive I'm sure. More info on the official forum, https://autohotkey.com/boards/viewtopic.php?f=14&t=15062

You can try the portable / binary versions which only have the autohotkey.exe and check those on virustotal

**Comment by Lexikos** [comment]
The same file now [shows a detection rate of 3 / 55](https://www.virustotal.com/en/file/a95c1d32b669d95ce6c2a0e3cc1467b226fba3a6b6a7a4fd675fd16115cb2365/analysis/1466217350/) (with only 1 AV in common). The v1.1.24.00 installer [shows 1 / 55](https://www.virustotal.com/en/file/a32b2ac34e0e57c61ef4805c972d970a96b3a7c788a626352d6ff24bb7237410/analysis/). These are false positives. They can sometimes be worked around by changing compilers, switching self-extracting binaries for the installer (as was done in v1.1.23.04), or other random changes, but ultimately the fault lies with the antivirus software/virus definitions.
