### ISSUE TITLE
alpha missing command Process

### ISSUE THREAD

**Issue by zhaozg** [Lexikos/AutoHotkey_L#56]
Error: Call to nonexistent function:
Process,Exit,...
Process,Close,...

**Comment by Lexikos** [comment]
It is not "missing". It was replaced. See [v2-changes](https://autohotkey.com/v2/v2-changes.htm).

**Comment by zhaozg** [comment]
and http://lexikos.github.io/v2/docs/commands/Process.htm too old.

**Comment by zhaozg** [comment]
Please show me simple example about Process,Exit and Process,Close
