### ISSUE TITLE
Gui doesn't adjust to Tab3 

### ISSUE THREAD

**Issue by T-vK** [Lexikos/AutoHotkey_L#57]
When creating a Gui with a Tab3 control the Gui doesn't ensure that the control is visible. Tab2 does not have this issue.

```
Gui, Add, Tab3,, General|View|Appearance|Settings
Gui, Show
```
results in this:  
![Tab3 screenshot](http://250kb.de/u/160525/p/f4jiQwu7sDjh.png)

```
Gui, Add, Tab2,, General|View|Appearance|Settings
Gui, Show
```
results in this:  
![Tab2 screenshot](http://250kb.de/u/160525/p/3km9E8GwdlPp.png)

**Comment by Lexikos** [comment]
When you do not specify a size for the control, Tab3 autosizes to its content whereas Tab and Tab2 have a fixed default size.  It seems that I forgot to include this in the documentation, but there are details in the [initial test release post](https://autohotkey.com/boards/viewtopic.php?p=75750#p75750).

I suppose that it would be reasonable to give the control a default size when no controls are present, if only for testing before you add controls to the GUI.

**Comment by Lexikos** [comment]
Oops, now that I've actually tested, I see that the control is given an arbitrary default size when no controls are present, but as you said, the problem is with the GUI sizing.  If you specify an adequate size for the GUI, the control will be visible.

Still, the problem appears to occur only if the tab control is empty.

**Comment by Lexikos** [comment]
My previous comment was actually incorrect: the control is always given an arbitrary default size, and when no controls were present, the autosizing was overriding the default size and making the control empty. But if you specified a GUI size, Tab3 autosizing was erroneously skipped.

**Comment by T-vK** [comment]
I see, thanks for clarifying.
