### ISSUE TITLE
Compiling for Linux

### ISSUE THREAD

**Issue by SuicSoft** [Lexikos/AutoHotkey_L#58]
How can I get this compiled for Linux ?

**Comment by perfaram** [comment]
Basically... You can't. AHK relies heavily on Windows system calls, and all its automation features are powered by functions and libraries which do not exist on Linux.

**Comment by joedf** [comment]
The closest things yet are:
- IronAHK
- AutoKey
- PyAHK
:/

**Comment by joedf** [comment]
A personal favourite is Javauto :)
