### ISSUE TITLE
Ignore a Line Containing Spaces Only?

### ISSUE THREAD

**Issue by lmstearn** [Lexikos/AutoHotkey_L#59]
Hi there! Very minor issue. Some of the [tutorials at the forum ](https://autohotkey.com/boards/viewtopic.php?f=3&t=4211&p=103540#p103540)have spaces where there is only supposed to be a CR/LF. Is it possible for the compiler to just ignore a line like that?
Thanks.

**Comment by Lexikos** [comment]
Leading and trailing spaces (and therefore blank lines) are already ignored, unless you are using a continuation section **and have explicitly requested trailing spaces to be kept** (RTrim0). So unless I'm missing something, your suggested change is very unlikely to have a positive effect.

Aside from that, changing the behaviour of the program to compensate for a minor forum bug is a terrible idea.

**Comment by lmstearn** [comment]
Running 1.1.24.01 in N++. Copy scripts from tutorials in and run no switches.
Found out what the culprit was on the forum software:
&nbsp; Hex A0
...
Yes, it's a terrible idea, but what else can a newb do?

**Comment by Lexikos** [comment]
I tested on IE, Chrome, Firefox and Edge, and only Edge returned non-breaking spaces. The other three returned regular spaces.

> what else can a newb do?

Ask for the **actual** bug to be fixed, obviously.
