### ISSUE TITLE
How "Send" works?

### ISSUE THREAD

**Issue by BladeMight** [Lexikos/AutoHotkey_L#61]
I was writing an C# app which was using SendInput to send Keyboard down/up, but the only thing that not worked is <kbd>Alt</kbd>+<kbd>Numpad0~9</kbd>,it just sends blink sound, in AutoHotkey it works.
How do your `Send` works? What it uses, etc. could you tell me? :sos: 

Thanks.

**Comment by Lexikos** [comment]
1. Your request does not belong here, as an Issue.
2. You can find the answer yourself by searching the source code (for "SendASC").
3. It works by calling keybd_event or SendInput.

**Comment by BladeMight** [comment]
> Your request does not belong here, as an Issue.
But there is a `Label` **question**

> You can find the answer yourself by searching the source code (for "SendASC").
It works by calling keybd_event or SendInput.

OK, thanks for the tip.

**Comment by Lexikos** [comment]
> But there is a `Label` **question**

No, [there are **no** labels](https://github.com/Lexikos/AutoHotkey_L/labels).

**Comment by BladeMight** [comment]
Sorry, i thinked that these labels availbe for all github repositories...

**Comment by BladeMight** [comment]
Found it, i should use keybd_event with MapVirtualKey.

**Comment by Lexikos** [comment]
As I said, it works by calling keybd_event **or SendInput**. If your code using SendInput didn't work, it's not because you were using SendInput.

**Comment by BladeMight** [comment]
Maybe if i add MapVirtualKey to INPUT's scan it will work too...

**Comment by BladeMight** [comment]
> Maybe if i add MapVirtualKey to INPUT's scan it will work too...

Yes, thats it! Solved, thanks for help.
