### ISSUE TITLE
Escape stops working

### ISSUE THREAD

**Issue by guilhas** [Lexikos/AutoHotkey_L#63]
Hello,

If I create a script with only:

> Escape & a::MsgBox, test A

Escape key stops working (Example Ctrl + Shift + Escape > Should open Task Manager)

But if I create a script like this:
> ~Escape & e:: MsgBox, test E
> Escape & a::MsgBox, test A

Escape continues to work fine.

Windows 7 64bit
AutoHotkey v1.1.24.01

**Comment by Lexikos** [comment]
That is the intended and documented behaviour.

**Comment by guilhas** [comment]
Could you please point me where?

I can only find escape characters.

**Comment by Lexikos** [comment]
It has nothing to do with Escape. Refer to the documentation for custom combinations and tilde.
