### ISSUE TITLE
[BUG] IfWinExist not detecting minimized Windows UWP/Modern Apps (Win10)

### ISSUE THREAD

**Issue by jtbrown3** [Lexikos/AutoHotkey_L#67]
Now that I'm using a few Windows UWP/Modern Apps, I'm noticing that the AutoHotkey IfWinExist & WinRestore (and other related commands) are not detecting these app windows when they are minimized (normal and maximized states are properly detected).

To demonstrate this error, I created a simple demo script (attached) that: 1) opens the Windows 10 'Calculator' UWP App, 2) Detects the window properly using IfWinExist, 3) Minimizes it, and 4) tries to re-detect the same window with the IfWinExist command. (which fails).

[IfWinExistErrorUWP.zip](https://github.com/Lexikos/AutoHotkey_L/files/768199/IfWinExistErrorUWP.zip)

If this irregularity could be resolved/fixed, I'm sure many would appreciate it! :)
-JT

My System Info:  Windows 10-64Bit Version 1607 (AU)
Latest AutoHotkey v1.1.24.05

**Comment by Lexikos** [comment]
It is not a bug. While the window is minimised, it does not meet the criteria you specified.

UWP apps are not Win32 apps. The framework manages windows in some way that probably isn't documented very well. Observation with Spy++ shows that the app owns one window of class `Windows.UI.Core.CoreWindow`. When the window is visible, this window is a child of the `ApplicationFrameWindow`. When the window is minimised, the "core window" is removed from the "frame window" and becomes a top-level window.

The source of the text matched by *WinText* is in fact the core window's title. When the frame window has no child windows, it has no text elements.

`Calculator ahk_class ApplicationFrameWindow` matches the frame window regardless of whether it is minimised. In other words, use WinTitle, not WinText.
