### ISSUE TITLE
Round() to a wrong result for some special math expression

### ISSUE THREAD

**Issue by lxydotcom** [Lexikos/AutoHotkey_L#69]
msgbox, % Round(54.85 * 0.9, 2) " vs " Round(74.85 * 0.9, 2)

It will display such result:
49.37 vs 67.36

"67.36" seems wrong

**Comment by joedf** [comment]
exactly 67.365 ...
worst case do this `Round((74.85 * 0.9) + 0.001,2)` ?

**Comment by Lexikos** [comment]
It's not a bug.  It's a common artefact of the binary floating point number format.

    SetFormat FloatFast, 0.15
    msgbox, % 54.85 * 0.9 " vs " 74.85 * 0.9

**Comment by lxydotcom** [comment]
http://stackoverflow.com/questions/588004/is-floating-point-math-broken

**Comment by lxydotcom** [comment]
One workaround maybe: Round(74.85 * 0.9 + 0.0000001, 2)
