### ISSUE TITLE
ByRef on object members doesn't work

### ISSUE THREAD

**Issue by buliasz** [Lexikos/AutoHotkey_L#71]
When you pass object member variable to function, with ByRef parameter, it doesn't change the value.
Try this simple code:
```
obj := {val:4}
IncVariable(obj.val)
MsgBox(obj.val)
return

IncVariable(ByRef variable) {
	++variable
}
```
You will get "4" result instead of "5".

**Comment by hi5** [comment]
Are you sure your syntax is correct? I don't think you can use ByRef like that + MsgBox has error for example.

    obj := {val:4}
    IncVariable(obj)
    MsgBox % (obj.val)
    return
    
    IncVariable(ByRef obj) {
    	obj.val++
    }

In general: Posting on autohotkey.com/boards/ (no registration required) may get you more/better/faster answers - see my comment [here](https://github.com/Lexikos/AutoHotkey_L/issues/70#issuecomment-285871040)

**Comment by Lexikos** [comment]
From the first page of [Google results](https://www.google.com/search?q=site:autohotkey.com+byref+object+member):
[ByRef Parameter fails on Array/Object-Fields](https://autohotkey.com/board/topic/71101-byref-parameter-fails-on-arrayobject-fields/)
[byref param clarification](https://autohotkey.com/boards/viewtopic.php?t=11345)

In short,
> Fields of objects are not considered variables for the purposes of ByRef. For example, if foo.bar is passed to a ByRef parameter, it will behave as though ByRef was omitted.

From [ByRef Parameters](https://autohotkey.com/docs/Functions.htm#ByRef).
