### ISSUE TITLE
Invalid option of GUI causes the script statement in memory changed

### ISSUE THREAD

**Issue by lxydotcom** [Lexikos/AutoHotkey_L#73]
```
^s::
Gui, Add, Edit, vMyVar W200 H50, edit text
Gui, Show
return

^d::
Gui, Destroy
return
```
---------
If triggering the hotkey ctrl-s twice, the vMyVar will be invalid option at the second time, which causes the following options W200 H50 to be removed from the script statement in memory. You can see the statement changed in error dialog.

Also, you can trigger ctrl-d then ctrl-s after that to see the change behavior of UI.

Though the above code is not normal logical, but changing statement looks so strange.

**Comment by Lexikos** [comment]
Incidentally, I fixed a similar issue in the v2 (alpha-gui) branch recently but didn't think to check whether the v1 branch was affected.

**Comment by Lexikos** [comment]
6ca8dba fixes this.
