### ISSUE TITLE
Possible variable evaluation-with-brackets bug

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [Lexikos/AutoHotkey_L#74]
I may have a found a bug, but my coding skill is low, and the script in question I've adapted from someone else. Anyhow, the following works as expected.

```
GetKeyState, EWD_LButtonState, LButton, P
if EWD_LButtonState = U
	{
		SetTimer, seeIfWindowDragOver_timed, off
		; Button has been released, so drag is complete.
		SetBatchLines, 10ms ; return to normal speed
	}
```

And the following does not, in that the bracketed code doesn't execute when 'EWD_LButtonState = U' (and the same happens even if I remove the space after 'U').

```
GetKeyState, EWD_LButtonState, LButton, P
if ( EWD_LButtonState = U )
	{
		SetTimer, seeIfWindowDragOver_timed, off
		; Button has been released, so drag is complete.
		SetBatchLines, 10ms ; return to normal speed
	}
```

Autohotkey1.1.25.00 on Windows x64 8.1.

**Comment by Lexikos** [comment]
These are two different types of IF statements. In the first case U is literal text; in the second, a variable. It's not a bug.

**Comment by ACinnamonUserInUK** [comment]
The brackets made `U` into a variable? I would never have guessed that!
