### ISSUE TITLE
ahk script is disabled in PyCharm

### ISSUE THREAD

**Issue by wolfand11** [Lexikos/AutoHotkey_L#79]
my ahk script work well, except in PyCharm IDE.  ahk script as bellow,
```
Alt::Control    ; change alt to control
Capslock::Alt   ; change Caps Lock to alt
```

PyCharm verison is PyCharm 2017.1.3
the AHK version is 1.1.24.03

**Comment by Lexikos** [comment]
This issue tracker is not for getting assistance using the program. For that, try the [AutoHotkey forums](https://autohotkey.com/boards/).
